openapi: 3.1.0
info:
  title: E-commerce Cart API
  description: API for managing user shopping carts in an e-commerce application
  version: 1.0.0
servers:
  - url: http://localhost:8000/api
paths:
  /cart:
    get:
      summary: Get authenticated user's cart
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CartResponse'
    post:
      summary: Create a new cart
      security:
        - BearerAuth: []
      responses:
        '201':
          description: Cart created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CartCreationResponse'
  /cart/{cartId}/items:
    post:
      summary: Add a new product to the cart
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: cartId
          required: true
          schema:
            type: integer
          description: ID of the cart
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddCartItemRequest'
      responses:
        '201':
          description: Item added successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CartItemResponse'
    delete:
      summary: Clear all items from the cart
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: cartId
          required: true
          schema:
            type: integer
          description: ID of the cart
      responses:
        '204':
          description: Cart cleared successfully
  /cart/{cartId}/items/{productId}:
    put:
      summary: Update the quantity of a specific product in the cart
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: cartId
          required: true
          schema:
            type: integer
          description: ID of the cart
        - in: path
          name: productId
          required: true
          schema:
            type: integer
          description: ID of the product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateCartItemQuantityRequest'
      responses:
        '200':
          description: Item quantity updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CartItemResponse'
    delete:
      summary: Remove a specific product from the cart
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: cartId
          required: true
          schema:
            type: integer
          description: ID of the cart
        - in: path
          name: productId
          required: true
          schema:
            type: integer
          description: ID of the product
      responses:
        '204':
          description: Product removed successfully
    
  /cart/{cartId}:
    delete:
      summary: Delete a specific cart
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: cartId
          required: true
          schema:
            type: integer
          description: ID of the cart
      responses:
        '204':
          description: Cart deleted successfully
  /cart/{cartId}/checkout:
    post:
      summary: Checkout from the cart
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: cartId
          required: true
          schema:
            type: integer
          description: ID of the cart
      responses:
        '201':
          description: Order created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CheckoutResponse'
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
  schemas:
    CartResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
        data:
          $ref: '#/components/schemas/Cart'
    Cart:
      type: object
      properties:
        id:
          type: integer
        createdAt:
          type: string
        items:
          type: array
          items:
            $ref: '#/components/schemas/CartItem'
        total:
          type: integer
    CartItem:
      type: object
      properties:
        id:
          type: integer
        quantity:
          type: integer
        name:
          type: string
        price:
          type: string
        imageUrl:
          type: string
        subtotal:
          type: integer
    CartCreationResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
        data:
          $ref: '#/components/schemas/CartCreationData'
    CartCreationData:
      type: object
      properties:
        id:
          type: integer
        createdAt:
          type: string
    AddCartItemRequest:
      type: object
      properties:
        id:
          type: integer
        quantity:
          type: integer
    CartItemResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
        data:
          $ref: '#/components/schemas/CartItem'
    UpdateCartItemQuantityRequest:
      type: object
      properties:
        quantity:
          type: integer
    CheckoutResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string